title: Timo Berg
url: "https://timo-berg.github.io/researcher/"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "CV_Timo_Berg.pdf"
 - name: "Orangutan"
   link: "orangutan"
 - name: "Contact"
   link: "contact"
